[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add sdl2-dev sdl2_image-dev sdl2_mixer-dev sdl2_ttf-dev libjpeg-turbo-dev freetype-dev"
